apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2022-07-27T14:00:19Z"
  generation: 12
  name: pacman
  namespace: argocd
  resourceVersion: "1462"
  uid: d3d739b3-8f53-47ff-8c22-2166397715b1
spec:
  destination:
    namespace: pacman-argo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/tiagoafonsoalves/pacmanOps
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
status:
  health:
    status: Healthy
  history:
  - deployStartedAt: "2022-07-27T14:00:20Z"
    deployedAt: "2022-07-27T14:00:23Z"
    id: 0
    revision: 5c93bc5d7d1b3174e414e06378cd116361d1b87d
    source:
      path: .
      repoURL: https://github.com/tiagoafonsoalves/pacmanOps
      targetRevision: HEAD
  operationState:
    finishedAt: "2022-07-27T14:00:23Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        revision: 5c93bc5d7d1b3174e414e06378cd116361d1b87d
        syncOptions:
        - CreateNamespace=true
    phase: Succeeded
    startedAt: "2022-07-27T14:00:20Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Succeeded
        kind: Namespace
        message: namespace/pacman-argo created
        name: pacman-argo
        namespace: ""
        status: Synced
        syncPhase: PreSync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Namespace
        message: namespace/pacman-namespace configured
        name: pacman-namespace
        namespace: pacman-argo
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/pacman-clusterip-service configured
        name: pacman-clusterip-service
        namespace: pacman-namespace
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/pacman-deployment configured
        name: pacman-deployment
        namespace: pacman-namespace
        status: Synced
        syncPhase: Sync
        version: v1
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/pacman-ingress configured
        name: pacman-ingress
        namespace: pacman-namespace
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 5c93bc5d7d1b3174e414e06378cd116361d1b87d
      source:
        path: .
        repoURL: https://github.com/tiagoafonsoalves/pacmanOps
        targetRevision: HEAD
  reconciledAt: "2022-07-27T14:00:23Z"
  resources:
  - kind: Namespace
    name: pacman-namespace
    status: Synced
    version: v1
  - health:
      status: Healthy
    kind: Service
    name: pacman-clusterip-service
    namespace: pacman-namespace
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: pacman-deployment
    namespace: pacman-namespace
    status: Synced
    version: v1
  - group: networking.k8s.io
    health:
      status: Healthy
    kind: Ingress
    name: pacman-ingress
    namespace: pacman-namespace
    status: Synced
    version: v1
  sourceType: Directory
  summary:
    externalURLs:
    - http://pacman.local/
    images:
    - ghcr.io/tiagoafonsoalves/pacman:2.0
  sync:
    comparedTo:
      destination:
        namespace: pacman-argo
        server: https://kubernetes.default.svc
      source:
        path: .
        repoURL: https://github.com/tiagoafonsoalves/pacmanOps
        targetRevision: HEAD
    revision: 5c93bc5d7d1b3174e414e06378cd116361d1b87d
    status: Synced
