apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman
  namespace: argocd
spec:
  destination:
    namespace: pacman-argo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deploy-pacman
    repoURL: https://github.com/tiagoafonsoalves/pacmanOps.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
